### ISSUE TITLE
Add base to the GHC version 

### ISSUE THREAD

**Issue by andygill** [damianfral/ghcaniuse#1]
http://damianfral.github.io/ghcaniuse/ is most useful! Thank you. 

Can you consider adding the ghc base number (aka what we say on cabal files) below the GHC version number?  Because the extensions go with the base as well as the compiler.

**Comment by damianfral** [comment]
Each GHC release comes with some boot libraries; the base library is one of them. If you wanna see which boot libraries were bundled with each GHC release, check: https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory .

As I understand, extensions are added/removed only when MAJOR or MINOR versions are changed. Boot libraries can be upgraded with any release, so, in order to keep things simple, I won't add base number. Agreed? :)
